import image1 from './img/tileDataImg1990_1.jpg';
import image2 from './img/tileDataImg1990_2.jpg';
import image3 from './img/tileDataImg1990_3.jpg';
import image4 from './img/tileDataImg1990_4.jpg';
import image5 from './img/tileDataImg1990_5.jpg';
import image6 from './img/tileDataImg1990_6.jpg';
import image7 from './img/tileDataImg1990_7.jpg';
// import image8 from './img/A.jpg';

const AgeList = [1990, 2000, 2010];

const tileData = [
  {
    id: '00001',
    img: image1,
    title: 'おどるポンポコリン',
    singer: 'B.B.クイーンズ',
    age: 1990,
    url: 'https://www.youtube.com/embed/-r4DIbDe0DM',
  },
  {
    id: '00002',
    img: image2,
    title: '浪漫飛行',
    singer: '米米CLUB',
    age: 1990,
    url: 'https://www.youtube.com/embed/cUygGkhQWDk',
  },
  {
    id: '00003',
    img: image3,
    title: '今すぐKiss Me',
    singer: 'LINDBERG',
    age: 1990,
    url: '',
  },
  {
    id: '00004',
    img: image4,
    title: 'さよなら人類',
    singer: 'たま',
    age: 1990,
    url: '',
  },
  {
    id: '00005',
    img: image5,
    title: 'OH YEAH！',
    singer: 'プリンセス・プリンセス',
    age: 1990,
    url: '',
  },
  {
    id: '00006',
    img: image6,
    title: 'Dear Friend',
    singer: '中森明菜',
    age: 1990,
    url: '',
  },
  {
    id: '00007',
    img: image7,
    title: '情熱の薔薇',
    singer: 'THE BLUE HEARTS',
    age: 1990,
    url: '',
  },
  {
    id: '00008',
    img: '',
    title: 'くちびるから媚薬',
    singer: '工藤静香',
    age: 1990,
    url: '',
  },
  {
    id: '00009',
    img: '',
    title: '真夏の果実',
    singer: 'サザンオールスターズ',
    age: 1990,
    url: '',
  },
  {
    id: '00010',
    img: '',
    title: 'イフ・ウイ・ホールド・オン・トゥゲザー',
    singer: 'ダイアナ・ロス',
    age: 1990,
    url: '',
  },
  {
    id: '00011',
    img: '',
    title: 'TSUNAMI',
    singer: 'サザンオールスターズ',
    age: 2000,
    url: '',
  },
  {
    id: '00012',
    img: '',
    title: '桜坂',
    singer: '福山雅治',
    age: 2000,
    url: '',
  },
  {
    id: '00013',
    img: '',
    title: 'Wait&See ～リスク～',
    singer: '宇多田ヒカル',
    age: 2000,
    url: '',
  },
  {
    id: '00014',
    img: '',
    title: 'Love, Day After Tomorrow',
    singer: '倉木麻衣',
    age: 2000,
    url: '',
  },
  {
    id: '00015',
    img: '',
    title: 'SEASONS',
    singer: '浜崎あゆみ',
    age: 2000,
    url: '',
  },
  {
    id: '00016',
    img: '',
    title: 'らいおんハート',
    singer: 'SMAP',
    age: 2000,
    url: '',
  },
  {
    id: '00017',
    img: '',
    title: '恋のダンスサイト',
    singer: 'モーニング娘。',
    age: 2000,
    url: '',
  },
  {
    id: '00018',
    img: '',
    title: '今夜月の見える丘に',
    singer: 'B`z',
    age: 2000,
    url: '',
  },
  {
    id: '00019',
    img: '',
    title: 'ちょこっとLOVE',
    singer: 'プッチモニ',
    age: 2000,
    url: '',
  },
  {
    id: '00020',
    img: '',
    title: 'NEO UNIVERSE／finale',
    singer: 'L`Arc～en～Ciel',
    age: 2000,
    url: '',
  },
  {
    id: '00021',
    img: '',
    title: 'めんどいからまだない',
    singer: 'まあ待て',
    age: 2010,
    url: '',
  },
];

const animeYoutubeLocalData = [
  'https://i.ytimg.com/vi/7FtgXtNPQGY/default.jpg',
  'https://i.ytimg.com/vi/uipcsm9IKoQ/default.jpg',
  'https://i.ytimg.com/vi/KNs0pQlJI94/default.jpg',
  'https://i.ytimg.com/vi/ReGOM4liVPs/default.jpg',
  'https://i.ytimg.com/vi/2oBHbrWM1WY/default.jpg',
  'https://i.ytimg.com/vi/3FtvmFAb9L8/default.jpg',
  'https://i.ytimg.com/vi/TMPbrFRrFi0/default.jpg',
  'https://i.ytimg.com/vi/a-67A1rl7QU/default.jpg',
  'https://i.ytimg.com/vi/v3ApcTz1lwE/default.jpg',
  'https://i.ytimg.com/vi/RwcE1GIoHY0/default.jpg',
  'https://i.ytimg.com/vi/Pr43Sayk37s/default.jpg',
  'https://i.ytimg.com/vi/Nxo9vH5-54I/default.jpg',
  'https://i.ytimg.com/vi/ckAJGAOOa1M/default.jpg',
  'https://i.ytimg.com/vi/o_KDbDQeofY/default.jpg',
  'https://i.ytimg.com/vi/jqU11N6hlyw/default.jpg',
  'https://i.ytimg.com/vi/vGJ4Q_lw3WI/default.jpg',
  'https://i.ytimg.com/vi/KdB7LnGEtxo/default.jpg',
  'https://i.ytimg.com/vi/kJXfiviTGCM/default.jpg',
  'https://i.ytimg.com/vi/8fCIcho7N4k/default.jpg',
  'https://i.ytimg.com/vi/jyrXuDw0ftQ/default.jpg',
  'https://i.ytimg.com/vi/V49KtL6cVDM/default.jpg',
  'https://i.ytimg.com/vi/UcrB_df_ZG8/default.jpg',
  'https://i.ytimg.com/vi/yYWEjgvNWtg/default.jpg',
  'https://i.ytimg.com/vi/07bswHElOjY/default.jpg',
  'https://i.ytimg.com/vi/OjvrBJkMTuk/default.jpg',
  'https://i.ytimg.com/vi/n6QatzbH4D4/default.jpg',
  'https://i.ytimg.com/vi/pCwfEB6PbFk/default.jpg',
  'https://i.ytimg.com/vi/T1as4cAEWSQ/default.jpg',
  'https://i.ytimg.com/vi/vDdJI6YTZno/default.jpg',
  'https://i.ytimg.com/vi/iz_sAWpBNrI/default.jpg',
  'https://i.ytimg.com/vi/vMadORbuwdE/default.jpg',
  'https://i.ytimg.com/vi/LLPv26YL4VU/default.jpg',
  'https://i.ytimg.com/vi/Wxr0-FsjKUY/default.jpg',
  'https://i.ytimg.com/vi/mwNsx87OUxo/default.jpg',
  'https://i.ytimg.com/vi/5Jxw_ZMn-10/default.jpg',
  'https://i.ytimg.com/vi/XSUjn_dn6uQ/default.jpg',
  'https://i.ytimg.com/vi/gdpR4flD84A/default.jpg',
  'https://i.ytimg.com/vi/oNnXrQgoqXI/default.jpg',
  'https://i.ytimg.com/vi/fRVj2zFlpyM/default.jpg',
  'https://i.ytimg.com/vi/OIoZrftDKhc/default.jpg',
];

export default { tileData, AgeList, animeYoutubeLocalData };
